import javax.swing.text.View

/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class ShiroSecurityFilters {
    def filters = {
        all(uri: "/**") {
            before = {
                // Ignore direct views (e.g. the default main index page).
                if (!controllerName || controllerName == 'assets') return true
                if(controllerName.contains('category') && actionName == 'index') return true
                if(controllerName.contains('location') && actionName == 'index') return true
                if(controllerName.contains('restaurant') && actionName == 'index') return true
                // Access control by convention.
                accessControl()
            }
        }
    }
}
